project-sunbird/sunbird-content-editor

app/scripts/framework/service/assessment-service.js
test_framework/scripts/service/assessment-service.spec.js

https://project-sunbird.atlassian.net/browse/SB-4910

Issue #593 feat: Delete question service in assessment service

---

gulpfile.js
webpack.config.js
webpack.plugin.config.js

@pallakartheekreddy 
This path for Read-along bug fix

Semantic bug fix

---

app/libs/alignment-guidelines.js
app/scripts/contenteditor/manager/stage-manager.js
webpack.config.js

https://project-sunbird.atlassian.net/browse/SB-3967

Alignment guidelines for objects on a slide

---

app/scripts/contenteditor/base-plugin.js
app/scripts/contenteditor/manager/stage-manager.js

JIRA Issue : https://project-sunbird.atlassian.net/browse/SB-5876
Pragma value need to set based on what plugin will send

Pragma changes

---

app/styles/content-editor.css

Removed richtext css from framework
Please merge Below PR also with this PR as all are related to richtext else richtext functionality will break
https://github.com/project-sunbird/sunbird-content-player/pull/47
https://github.com/project-sunbird/sunbird-content-plugins/pull/41

Issue #SB-7213 fix: Richtext WYSIWYG

---

app/scripts/contenteditor/manager/stage-manager.js
karmaconf.js
test/scripts/CE-integration.spec.js

JIRA issue: https://project-sunbird.atlassian.net/browse/SB-7357

Relationship between Item/Question set and Content

---

app/scripts/framework/service/meta-service.js

Jira Issue: https://project-sunbird.atlassian.net/browse/SB-7328

Issue #SB-7328 feature: Add video to a slide by using YouTube URL

---

app/scripts/contenteditor/manager/stage-manager.js

Jira Issue : https://project-sunbird.atlassian.net/browse/SB-9110

editorState stage mismatch

---

karmaconf.pluginframework.js
test_framework/scripts/service/user-service.spec.js

Issue: https://project-sunbird.atlassian.net/browse/SB-10014
User-Service Code Coverage: 100%
@pallakartheekreddy

Issue #SB-10014 feat: Added test cases for the user-service

---

app/scripts/framework/service/meta-service.js

[JIRA LINK](https://project-sunbird.atlassian.net/browse/SB-10218)

added youtube and google drive sharable video services

---

app/scripts/contenteditor/manager/stage-manager.js

Reverts project-sunbird/sunbird-content-editor#47

Revert "Issue #SB-10311 fix: Update stageicons according to stages"

---

app/index.html

**Ref:** https://project-sunbird.atlassian.net/browse/SB-10564
**Description:**
Resource editor > Slide navigation : tooltips for Delete & Copy.

Issue ‎#SB-10564 fix:Added tooltip for copy and delete in resouce editor

---

app/scripts/contenteditor/service/telemetry-service.js

https://project-sunbird.atlassian.net/browse/SB-10919

Issue #SB-10919 fix: added duration to impression method

---

app/scripts/angular/controller/main.js

https://project-sunbird.atlassian.net/browse/SB-10919

Issue #SB-10919 fix: error event fixes

---

app/scripts/angular/controller/main.js

- [Issue LInk](https://project-sunbird.atlassian.net/browse/SB-11206)
- telemetry events for content and editor load time implemented.

Issue SB-11206 fix: telemetry start event and content load time fixes

---

app/scripts/contenteditor/manager/stage-manager.js
app/scripts/framework/service/content-service.js
webpack.plugin.config.js

Jira Issue: https://project-sunbird.atlassian.net/browse/SB-9873

Issue #SB-9873 feat: content service field  and stagemanager updated

---

gulpfile.js

- [Issue Link](https://project-sunbird.atlassian.net/browse/SB-12008)
- Asset browser will be loaded through Gulp task(packageCorePlugins).

Issue #SB-12008 feat: bundled video plugin

---

webpack.plugin.config.js

- [Issue Link](https://project-sunbird.atlassian.net/browse/SB-12008)

Issue #SB-11916 feat: bundled video and reviewercomments plugin

---

deploy/package.json

[JIRA LINK](https://project-sunbird.atlassian.net/browse/SB-12173)

Issue #SB-12173 fix; Version number fixed in deploy package.json

---

webpack.plugin.config.js

[JIRA LINK](https://project-sunbird.atlassian.net/browse/SB-13098)

Issue #SB-13098 fix: Coreplugins package for latest version of wordinfo plugin

---

app/scripts/contenteditor/service/telemetry-service.js

https://project-sunbird.atlassian.net/browse/SC-1050

 Issue #SC-1050 enhancement : To include context in interact event

---

app/scripts/contenteditor/service/telemetry-service.js
app/scripts/framework/service/iservice.js

https://project-sunbird.atlassian.net/browse/SC-1050

 Issue #SC-1050 fix : fixing overriding of global cdata

---

app/scripts/contenteditor/service/telemetry-service.js

https://project-sunbird.atlassian.net/browse/SC-1050

Issue #SC-1050, fix : added options for log event As well

---

app/scripts/contenteditor/service/telemetry-service.js

https://project-sunbird.atlassian.net/browse/SC-1050

Issue #SC-1050, fix : generating options data always with global cdata
